[package]
name = "file_grouper"
version = "0.1.0"
authors = ["Guillaume DE LAZZER <guillaume@de-lazzer.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argparse = "0.2.2"
glob = "0.3.0"